"use client";

import { FormEvent, useMemo, useState } from "react";
import { Booking, BookingStatus, Customer, Driver, Vehicle, customers, drivers, formatDateTime, initialBookings, localIso, money, overlaps, vehicles } from "./demo-data";

type Tab="Dashboard"|"Bookings"|"Fleet Calendar"|"Availability Checker"|"Trips"|"Customers"|"Vehicles"|"Drivers"|"Payments"|"Reports"|"Notifications"|"Website Enquiries"|"Settings";
type BookingDraft={customerName:string;phone:string;whatsapp:string;email:string;from:string;to:string;pickup:string;returnAt:string;vehicleId:string;driverId:string;rate:number;estimatedKm:number;advance:number;notes:string};
type Enquiry={id:string;name:string;phone:string;route:string;tripType:string;date:string;status:"New"|"Contacted"};

const defaultDraft:BookingDraft={customerName:"Rahul Sharma",phone:"98260 45678",whatsapp:"98260 45678",email:"rahul.sharma@example.in",from:"Vijay Nagar, Indore",to:"Jaipur",pickup:"2026-08-22T08:00",returnAt:"2026-08-24T20:00",vehicleId:"VEH-04",driverId:"DRV-04",rate:22,estimatedKm:750,advance:8500,notes:"Customer prefers an experienced highway driver."};
const fixedNow=new Date("2026-08-21T10:30:00");
const statusColor:Record<BookingStatus,string>={Enquiry:"grey",Confirmed:"blue","Vehicle Assigned":"purple","On Trip":"navy",Completed:"green",Cancelled:"red",Reserved:"purple"};
const navItems:{tab:Tab;icon:string}[]=[{tab:"Dashboard",icon:"▦"},{tab:"Bookings",icon:"▣"},{tab:"Fleet Calendar",icon:"▤"},{tab:"Availability Checker",icon:"⌕"},{tab:"Trips",icon:"↗"},{tab:"Customers",icon:"♙"},{tab:"Vehicles",icon:"▰"},{tab:"Drivers",icon:"♟"},{tab:"Payments",icon:"₹"},{tab:"Reports",icon:"▥"},{tab:"Notifications",icon:"◇"},{tab:"Website Enquiries",icon:"✉"},{tab:"Settings",icon:"⚙"}];

export default function Home(){
 const [mode,setMode]=useState<"website"|"dashboard">("website");
 const [bookings,setBookings]=useState<Booking[]>(initialBookings);
 const [enquiries,setEnquiries]=useState<Enquiry[]>([{id:"WEB-026",name:"Kunal Mehta",phone:"98930 11223",route:"Indore → Mumbai",tripType:"Round Trip",date:"21 Aug, 9:42 AM",status:"New"},{id:"WEB-025",name:"Ritu Jain",phone:"98262 77890",route:"Indore → Ujjain",tripType:"One Way",date:"21 Aug, 8:15 AM",status:"New"}]);
 return mode==="website"?<Website onDashboard={()=>setMode("dashboard")} onEnquiry={e=>setEnquiries(p=>[e,...p])}/>:<Operations bookings={bookings} setBookings={setBookings} enquiries={enquiries} setEnquiries={setEnquiries} onWebsite={()=>setMode("website")}/>;
}

function Brand(){return <div className="brand"><span>S</span><div><b>Shreenath</b><small>Tours & Travels</small></div></div>}

function Website({onDashboard,onEnquiry}:{onDashboard:()=>void;onEnquiry:(e:Enquiry)=>void}){
 const [sent,setSent]=useState(false);
 function submitEnquiry(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);onEnquiry({id:`WEB-${String(Date.now()).slice(-3)}`,name:String(f.get("name")),phone:String(f.get("phone")),route:`${f.get("from")} → ${f.get("to")}`,tripType:String(f.get("type")),date:"Just now",status:"New"});setSent(true);e.currentTarget.reset();}
 return <main className="site">
  <nav className="siteNav wrap"><Brand/><div className="siteLinks"><a href="#services">Services</a><a href="#fleet">Our fleet</a><a href="#about">About</a><a href="#contact">Contact</a></div><div className="siteActions"><button className="linkBtn" onClick={onDashboard}>Staff dashboard</button><a className="btn outlineBtn" href="https://wa.me/919826012345" target="_blank">WhatsApp</a><a className="btn" href="#book">Book your trip</a></div></nav>
  <section className="siteHero"><div className="wrap heroGrid"><div className="heroCopy"><span className="overline">INDORE&apos;S TRUSTED TRAVEL PARTNER</span><h1>Your Journey.<br/><em>Our Responsibility.</em></h1><p>Reliable cars, professional drivers and comfortable travel for local, airport and outstation trips.</p><div className="heroActions"><a className="btn heroBtn" href="#book">Book your trip <b>→</b></a><a className="btn outlineBtn heroBtn" href="https://wa.me/919826012345" target="_blank">WhatsApp us</a></div><div className="trustRow"><span>✓ Verified drivers</span><span>✓ Transparent pricing</span><span>✓ 24×7 support</span></div></div><div className="heroVisual"><div className="heroPhoto"><div><span>INDORE</span><b>Comfort in every kilometre</b></div></div><aside className="rating"><b>4.9</b><span>★★★★★<small>2,500+ happy travellers</small></span></aside></div></div><div className="wrap siteStats">{[["40+","Vehicles"],["5,000+","Trips completed"],["2,500+","Happy travellers"],["24×7","Booking support"]].map(x=><div key={x[1]}><b>{x[0]}</b><span>{x[1]}</span></div>)}</div></section>
  <section className="siteSection wrap" id="services"><div className="sectionTitle"><span className="overline">TRAVEL, DONE RIGHT</span><h2>A dependable car for every plan.</h2><p>One responsive team for local rides, business travel and long-distance journeys.</p></div><div className="serviceGrid">{[["Airport transfers","Flight-aware pickups with zero waiting stress.","From ₹899"],["Outstation journeys","Experienced route drivers for comfortable intercity travel.","From ₹12/km"],["Corporate travel","Reliable executive and employee transport solutions.","Monthly plans"],["Wedding transport","Coordinated premium fleets for every celebration.","Custom quote"]].map((x,i)=><article key={x[0]}><span className="serviceNo">0{i+1}</span><h3>{x[0]}</h3><p>{x[1]}</p><div><b>{x[2]}</b><a href="#book">Book now →</a></div></article>)}</div></section>
  <section className="fleetSection" id="fleet"><div className="wrap"><div className="sectionTitle"><span className="overline">OUR FLEET</span><h2>Clean, comfortable and trip-ready.</h2></div><div className="publicFleet">{[["Swift Dzire","4 seats","₹12/km"],["Maruti Ertiga","6 seats","₹16/km"],["Innova Crysta","7 seats","₹22/km"],["Tempo Traveller","17 seats","₹30/km"]].map((x,i)=><article key={x[0]}><div className={`fleetPhoto fp${i}`}/><span>{x[1]} · AC</span><h3>{x[0]}</h3><div><b>{x[2]}</b><a href="#book">Check availability</a></div></article>)}</div></div></section>
  <section className="aboutBand" id="about"><div className="wrap"><div><span className="overline">SINCE 2012</span><h2>Travel managed with care,<br/>from booking to final drop.</h2></div><p>Shreenath Tours & Travels operates a professionally maintained fleet across Indore and nearby cities. Every booking is monitored by our own operations team for punctual, safe and comfortable travel.</p></div></section>
  <section className="bookingSection" id="book"><div className="wrap bookingGrid"><div><span className="overline">REQUEST A BOOKING</span><h2>Tell us where you&apos;re going.</h2><p>Share the essentials. Our booking team will check the fleet and call you with the best vehicle and fare.</p><ul><li>Fast availability confirmation</li><li>No hidden charges</li><li>Driver details before departure</li></ul></div><form onSubmit={submitEnquiry}><div className="formGrid"><label>Your name<input required name="name" placeholder="Full name"/></label><label>Mobile number<input required name="phone" inputMode="tel" placeholder="10-digit number" pattern="[0-9 ]{10,12}"/></label><label>Pickup<input required name="from" placeholder="Pickup location"/></label><label>Destination<input required name="to" placeholder="Where are you going?"/></label><label>Trip type<select name="type"><option>One Way</option><option>Round Trip</option><option>Airport</option><option>Multi-Day</option></select></label><label>Pickup date<input required name="date" type="date" defaultValue="2026-08-22"/></label></div><button className="btn formSubmit">Check availability & request booking</button>{sent&&<div className="formSuccess">✓ Enquiry received. Our team will call you shortly.</div>}</form></div></section>
  <footer id="contact"><div className="wrap"><Brand/><p>Airport · Local · Outstation · Corporate · Wedding travel</p><div><a href="tel:+919826012345">+91 98260 12345</a><a href="https://wa.me/919826012345" target="_blank">WhatsApp</a><button onClick={onDashboard}>Staff login</button></div></div></footer>
 </main>
}

function Operations({bookings,setBookings,enquiries,setEnquiries,onWebsite}:{bookings:Booking[];setBookings:(v:Booking[]|((p:Booking[])=>Booking[]))=>void;enquiries:Enquiry[];setEnquiries:(v:Enquiry[]|((p:Enquiry[])=>Enquiry[]))=>void;onWebsite:()=>void}){
 const [tab,setTab]=useState<Tab>("Dashboard"),[menu,setMenu]=useState(false),[globalSearch,setGlobalSearch]=useState("");
 const [wizard,setWizard]=useState(false),[step,setStep]=useState(1),[draft,setDraft]=useState<BookingDraft>(defaultDraft),[conflict,setConflict]=useState<Booking|null>(null),[success,setSuccess]=useState<Booking|null>(null),[drawer,setDrawer]=useState<Booking|null>(null),[toast,setToast]=useState("");
 const amount=draft.rate*draft.estimatedKm, balance=Math.max(0,amount-draft.advance);
 const currentTrips=bookings.filter(b=>new Date(b.pickup)<=fixedNow&&new Date(b.returnAt)>=fixedNow&&b.status!=="Cancelled");
 const maintenanceNow=vehicles.filter(v=>v.maintenance&&overlaps(localIso(fixedNow),localIso(new Date(fixedNow.getTime()+60000)),v.maintenance.from,v.maintenance.to));
 const availableCount=vehicles.filter(v=>!currentTrips.some(b=>b.vehicleId===v.id)&&!maintenanceNow.some(m=>m.id===v.id)).length;
 const outstanding=bookings.filter(b=>b.status!=="Cancelled").reduce((s,b)=>s+(b.total-b.advance),0);
 const openWizard=(vehicleId?:string,pickup?:string,returnAt?:string)=>{const v=vehicles.find(x=>x.id===(vehicleId||draft.vehicleId));setDraft(p=>({...p,vehicleId:v?.id||p.vehicleId,driverId:v?.driverId||p.driverId,rate:v?.rate||p.rate,pickup:pickup||p.pickup,returnAt:returnAt||p.returnAt}));setStep(1);setConflict(null);setSuccess(null);setWizard(true)};
 function confirmBooking(){if(new Date(draft.returnAt)<=new Date(draft.pickup)){setToast("Return time must be later than pickup time.");return}const hit=bookings.find(b=>b.status!=="Cancelled"&&((b.vehicleId===draft.vehicleId||b.driverId===draft.driverId)&&overlaps(draft.pickup,draft.returnAt,b.pickup,b.returnAt)));if(hit){setConflict(hit);return}const customer=customers.find(c=>c.name.toLowerCase()===draft.customerName.toLowerCase());const booking:Booking={id:`STT-2026-${String(160+bookings.length).padStart(3,"0")}`,customerId:customer?.id||`CUS-NEW-${bookings.length}`,customerName:draft.customerName,phone:draft.phone,vehicleId:draft.vehicleId,driverId:draft.driverId,pickup:draft.pickup,returnAt:draft.returnAt,from:draft.from,to:draft.to,total:amount,advance:draft.advance,status:"Confirmed",source:"Phone"};setBookings(p=>[booking,...p]);setSuccess(booking);setConflict(null);setStep(5)}
 const alternatives=useMemo(()=>vehicles.filter(v=>v.id!==draft.vehicleId&&[vehicles.find(x=>x.id===draft.vehicleId)?.category,"Toyota Innova","Maruti Ertiga"].includes(v.category)&&!bookings.some(b=>b.status!=="Cancelled"&&(b.vehicleId===v.id||b.driverId===v.driverId)&&overlaps(draft.pickup,draft.returnAt,b.pickup,b.returnAt))&&!(v.maintenance&&overlaps(draft.pickup,draft.returnAt,v.maintenance.from,v.maintenance.to))).slice(0,3),[bookings,draft]);
 const searchResults=globalSearch.trim()?([...bookings.filter(b=>(b.id+b.customerName+b.phone).toLowerCase().includes(globalSearch.toLowerCase())).slice(0,3).map(b=>({label:`${b.id} · ${b.customerName}`,meta:`${b.from} → ${b.to}`,action:()=>{setDrawer(b);setGlobalSearch("")}})),...vehicles.filter(v=>(v.name+v.reg).toLowerCase().includes(globalSearch.toLowerCase())).slice(0,3).map(v=>({label:v.name,meta:v.reg,action:()=>{setTab("Vehicles");setGlobalSearch("")}})),...drivers.filter(d=>(d.name+d.phone).toLowerCase().includes(globalSearch.toLowerCase())).slice(0,2).map(d=>({label:d.name,meta:"Driver · "+d.phone,action:()=>{setTab("Drivers");setGlobalSearch("")}}))]):[];
 return <main className="ops"><aside className={menu?"sidebar open":"sidebar"}><div className="sidebarBrand"><Brand/><button onClick={()=>setMenu(false)}>×</button></div><nav>{navItems.map(n=><button key={n.tab} className={tab===n.tab?"active":""} onClick={()=>{setTab(n.tab);setMenu(false)}}><i>{n.icon}</i><span>{n.tab}</span>{n.tab==="Notifications"&&<b>5</b>}{n.tab==="Website Enquiries"&&enquiries.some(e=>e.status==="New")&&<b>{enquiries.filter(e=>e.status==="New").length}</b>}</button>)}</nav><button className="publicLink" onClick={onWebsite}>← Public website</button><div className="profile"><span>AS</span><div><b>Ankit Sharma</b><small>Owner · Super Admin</small></div></div></aside>
  <section className="workspace"><header className="topbar"><button className="menuBtn" onClick={()=>setMenu(true)}>☰</button><div className="universal"><span>⌕</span><input value={globalSearch} onChange={e=>setGlobalSearch(e.target.value)} placeholder="Search customer, mobile, booking, vehicle or driver"/>{searchResults.length>0&&<div className="searchDrop">{searchResults.map((r,i)=><button key={i} onClick={r.action}><b>{r.label}</b><small>{r.meta}</small></button>)}</div>}</div><div className="dateBox"><small>TODAY</small><b>21 Aug 2026</b></div><button className="bell" onClick={()=>setTab("Notifications")}>◇<b>5</b></button><div className="topUser"><span>AS</span><div><b>Ankit Sharma</b><small>Owner</small></div><i>⌄</i></div></header>
   <div className="pageHead"><div><span className="overline">SHREENATH OPERATIONS</span><h1>{tab}</h1><p>{tab==="Dashboard"?"Live business overview for Friday, 21 August 2026":pageSubtitle(tab)}</p></div><div>{tab!=="Availability Checker"&&<button className="btn secondaryBtn" onClick={()=>setTab("Availability Checker")}>⌕ Check availability</button>}<button className="btn" onClick={()=>openWizard()}>+ New booking</button></div></div>
   {tab==="Dashboard"&&<Dashboard bookings={bookings} available={availableCount} outstanding={outstanding} onTab={setTab} onBooking={setDrawer}/>} 
   {tab==="Fleet Calendar"&&<FleetCalendar bookings={bookings} onBooking={setDrawer} onSlot={openWizard}/>} 
   {tab==="Availability Checker"&&<AvailabilityChecker bookings={bookings} onSelect={(v,p,r)=>openWizard(v.id,p,r)}/>} 
   {tab==="Bookings"&&<BookingsPage bookings={bookings} onOpen={setDrawer} onNew={()=>openWizard()}/>} 
   {tab==="Vehicles"&&<VehiclesPage bookings={bookings}/>} 
   {tab==="Drivers"&&<DriversPage bookings={bookings}/>} 
   {tab==="Customers"&&<CustomersPage bookings={bookings} onNew={(c)=>{setDraft(p=>({...p,customerName:c.name,phone:c.phone,whatsapp:c.phone,email:c.email}));openWizard()}}/>}
   {tab==="Payments"&&<PaymentsPage bookings={bookings} onOpen={setDrawer} onToast={setToast}/>} 
   {tab==="Trips"&&<BookingsPage bookings={bookings.filter(b=>["Confirmed","On Trip","Vehicle Assigned"].includes(b.status))} onOpen={setDrawer} onNew={()=>openWizard()}/>} 
   {tab==="Website Enquiries"&&<EnquiriesPage enquiries={enquiries} setEnquiries={setEnquiries} onBooking={e=>{setDraft(p=>({...p,customerName:e.name,phone:e.phone,whatsapp:e.phone}));openWizard()}}/>}
   {tab==="Reports"&&<ReportsPage bookings={bookings} onToast={setToast}/>} 
   {tab==="Notifications"&&<NotificationsPage onNavigate={setTab}/>} 
   {tab==="Settings"&&<SettingsPage onToast={setToast}/>} 
  </section>
  {wizard&&<BookingWizard draft={draft} setDraft={setDraft} step={step} setStep={setStep} amount={amount} balance={balance} onClose={()=>setWizard(false)} onConfirm={confirmBooking} success={success}/>} 
  {conflict&&<ConflictModal conflict={conflict} draft={draft} alternatives={alternatives} onClose={()=>setConflict(null)} onAlternative={v=>{setDraft(p=>({...p,vehicleId:v.id,driverId:v.driverId,rate:v.rate}));setConflict(null);setStep(3)}}/>}
  {drawer&&<BookingDrawer booking={drawer} onClose={()=>setDrawer(null)} onDuplicate={()=>{setDraft({...defaultDraft,vehicleId:drawer.vehicleId,driverId:drawer.driverId,customerName:drawer.customerName,phone:drawer.phone,whatsapp:drawer.phone,from:drawer.from,to:drawer.to});setDrawer(null);openWizard(drawer.vehicleId)}}/>}
  {toast&&<div className="toast" onAnimationEnd={()=>setToast("")}>{toast}</div>}
 </main>
}

function pageSubtitle(tab:Tab){const map:Partial<Record<Tab,string>>={Bookings:"Manage every enquiry, booking and trip status.","Fleet Calendar":"See every vehicle, booking and free slot in one timeline.","Availability Checker":"Find the right free vehicle in seconds.",Vehicles:"Vehicle records, availability and compliance alerts.",Drivers:"Driver schedules, licences and trip assignments.",Payments:"Collections, balances and payment follow-ups.",Customers:"Customer history, value and upcoming travel.",Reports:"Business performance and export-ready reports."};return map[tab]||"Live operational records from one consistent source."}

function Dashboard({bookings,available,outstanding,onTab,onBooking}:{bookings:Booking[];available:number;outstanding:number;onTab:(t:Tab)=>void;onBooking:(b:Booking)=>void}){
 const upcoming=bookings.filter(b=>new Date(b.pickup)>fixedNow&&b.status!=="Cancelled").sort((a,b)=>+new Date(a.pickup)-+new Date(b.pickup));const current=bookings.filter(b=>new Date(b.pickup)<=fixedNow&&new Date(b.returnAt)>=fixedNow&&b.status!=="Cancelled");const todayRevenue=bookings.filter(b=>b.status!=="Cancelled"&&b.pickup.startsWith("2026-08-21")).reduce((s,b)=>s+b.total,0);const returning=current.filter(b=>b.returnAt.startsWith("2026-08-21"));
 const kpis=[{label:"Total fleet",value:"40",meta:"2 compliance alerts",tab:"Vehicles" as Tab,tone:"navy"},{label:"Available now",value:String(available),meta:"Ready to assign",tab:"Availability Checker" as Tab,tone:"green"},{label:"On trip",value:String(current.length),meta:"Across 6 cities",tab:"Trips" as Tab,tone:"blue"},{label:"Upcoming bookings",value:String(upcoming.length),meta:"Next 30 days",tab:"Bookings" as Tab,tone:"purple"},{label:"Today’s value",value:money(todayRevenue),meta:"Confirmed trips",tab:"Payments" as Tab,tone:"amber"},{label:"Outstanding",value:money(outstanding),meta:"Payment follow-up",tab:"Payments" as Tab,tone:"red"}];
 return <><div className="kpiGrid">{kpis.map(k=><button key={k.label} onClick={()=>onTab(k.tab)}><span className={`kpiIcon ${k.tone}`}>◆</span><small>{k.label}</small><strong>{k.value}</strong><em>{k.meta}</em><i>→</i></button>)}</div>
  <div className="dashTop"><section className="card availabilityOverview"><CardHead title="Fleet Availability Overview" sub="Next 7 days · all 40 vehicles" action="Open calendar" onAction={()=>onTab("Fleet Calendar")}/><div className="utilLegend"><span><i className="lgAvail"/>Available</span><span><i className="lgBook"/>Booked / On trip</span><span><i className="lgMaint"/>Maintenance</span></div><div className="utilChart">{[56,45,38,32,52,62,70].map((free,i)=><div key={i}><b><span style={{height:`${100-free}%`}}/><i style={{height:`${free}%`}}/></b><small>{["21 Fri","22 Sat","23 Sun","24 Mon","25 Tue","26 Wed","27 Thu"][i]}</small><em>{free}% free</em></div>)}</div><div className="demandNote"><span>!</span><p><b>High demand this weekend</b><small>Only 13–15 vehicles are available on 22–23 August.</small></p><button onClick={()=>onTab("Availability Checker")}>Check dates →</button></div></section>
  <section className="card departures"><CardHead title="Today’s Departures" sub={`${upcoming.filter(b=>b.pickup.startsWith("2026-08-21")).length} trips scheduled`} action="View trips" onAction={()=>onTab("Trips")}/>{upcoming.filter(b=>b.pickup.startsWith("2026-08-21")).slice(0,5).map(b=><button className="activityRow" key={b.id} onClick={()=>onBooking(b)}><time>{new Date(b.pickup).toLocaleTimeString("en-IN",{hour:"2-digit",minute:"2-digit",hour12:true})}</time><i/><p><b>{b.from.replace(", Indore","")} → {b.to}</b><span>{vehicles.find(v=>v.id===b.vehicleId)?.name} · {drivers.find(d=>d.id===b.driverId)?.name}</span></p><em>›</em></button>)}</section></div>
  <div className="dashBottom"><section className="card"><CardHead title="Vehicles Returning Today" sub="Turnaround and next-booking risk" action="Fleet status" onAction={()=>onTab("Vehicles")}/>{returning.length?returning.map(b=><button className="returnRow" key={b.id} onClick={()=>onBooking(b)}><span className="vehicleGlyph">▰</span><p><b>{vehicles.find(v=>v.id===b.vehicleId)?.name}</b><small>{b.to} → Indore</small></p><time>{new Date(b.returnAt).toLocaleTimeString("en-IN",{hour:"numeric",minute:"2-digit",hour12:true})}</time><em className="pill amber">Returning</em></button>):<Empty title="No vehicles due back today"/>}</section>
  <section className="card"><CardHead title="Pending Payments" sub="Highest priority collections" action="View payments" onAction={()=>onTab("Payments")}/>{bookings.filter(b=>b.total>b.advance&&b.status!=="Cancelled").sort((a,b)=>(b.total-b.advance)-(a.total-a.advance)).slice(0,4).map(b=><button className="paymentRow" key={b.id} onClick={()=>onBooking(b)}><span>{b.customerName.split(" ").map(x=>x[0]).join("")}</span><p><b>{b.customerName}</b><small>{b.id} · {b.to}</small></p><strong>{money(b.total-b.advance)}</strong></button>)}</section>
  <section className="card critical"><CardHead title="Critical Alerts" sub="Needs attention today" action="View all" onAction={()=>onTab("Notifications")}/>{[["Insurance expiry","Innova Crysta 07 · expires in 8 days","red"],["Tight schedule","Dzire 03 · only 45 min turnaround","amber"],["New web enquiries","2 customers awaiting a call","blue"]].map(a=><button key={a[0]} onClick={()=>onTab(a[0]==="New web enquiries"?"Website Enquiries":"Notifications")}><i className={a[2]}>!</i><p><b>{a[0]}</b><small>{a[1]}</small></p><span>›</span></button>)}</section></div></>;
}

function CardHead({title,sub,action,onAction}:{title:string;sub:string;action:string;onAction:()=>void}){return <div className="cardHead"><div><h3>{title}</h3><p>{sub}</p></div><button onClick={onAction}>{action} →</button></div>}

function FleetCalendar({bookings,onBooking,onSlot}:{bookings:Booking[];onBooking:(b:Booking)=>void;onSlot:(vehicleId:string,pickup:string,returnAt:string)=>void}){
 const [view,setView]=useState<"Day"|"Week"|"Month">("Week"),[category,setCategory]=useState("All"),[branch,setBranch]=useState("All"),[onlyAvailable,setOnlyAvailable]=useState(false),[status,setStatus]=useState("All");
 const start=new Date("2026-08-21T00:00"), count=view==="Day"?1:view==="Week"?7:31;const days=Array.from({length:count},(_,i)=>new Date(start.getFullYear(),start.getMonth(),start.getDate()+i));
 const filtered=vehicles.filter(v=>(category==="All"||v.category===category)&&(branch==="All"||v.branch===branch)&&(!onlyAvailable||!bookings.some(b=>b.vehicleId===v.id&&days.some(d=>overlaps(localIso(d),localIso(new Date(d.getTime()+86400000)),b.pickup,b.returnAt))))&&(status==="All"||status==="Maintenance"&&!!v.maintenance));
 const cols=`220px repeat(${count}, ${view==="Month"?86:120}px)`;
 return <section className="calendarPage"><div className="calendarToolbar card"><div className="segmented">{(["Day","Week","Month"] as const).map(v=><button className={view===v?"active":""} key={v} onClick={()=>setView(v)}>{v}</button>)}</div><label>Category<select value={category} onChange={e=>setCategory(e.target.value)}><option>All</option>{Array.from(new Set(vehicles.map(v=>v.category))).map(c=><option key={c}>{c}</option>)}</select></label><label>Status<select value={status} onChange={e=>setStatus(e.target.value)}><option>All</option><option>Maintenance</option></select></label><label>Branch<select value={branch} onChange={e=>setBranch(e.target.value)}><option>All</option><option>Indore HQ</option><option>Ujjain</option></select></label><label className="check"><input type="checkbox" checked={onlyAvailable} onChange={e=>setOnlyAvailable(e.target.checked)}/> Available vehicles only</label><button className="clearBtn" onClick={()=>{setCategory("All");setStatus("All");setBranch("All");setOnlyAvailable(false)}}>Clear filters</button></div>
  <div className="legend card"><b>Colour legend</b>{[["available","Available"],["reserved","Reserved"],["booked","Booked"],["ontrip","On Trip"],["returning","Returning Today"],["maintenance","Maintenance"],["unavailable","Unavailable"]].map(x=><span key={x[0]}><i className={x[0]}/>{x[1]}</span>)}<em>Click a free slot to create a booking</em></div>
  <div className="resourceWrap card"><div className="resourceGrid" style={{minWidth:220+count*(view==="Month"?86:120)}}><div className="resourceHeader" style={{gridTemplateColumns:cols}}><b className="vehicleHeader">Vehicle</b>{days.map((d,i)=><b className={`${i===0?"today":""} ${d.getDay()===0||d.getDay()===6?"weekend":""}`} key={d.toISOString()}><span>{d.toLocaleDateString("en-IN",{weekday:"short"})}</span>{d.getDate()} {d.toLocaleDateString("en-IN",{month:"short"})}</b>)}</div>{filtered.map(v=><ResourceRow key={v.id} vehicle={v} days={days} cols={cols} bookings={bookings.filter(b=>b.vehicleId===v.id&&b.status!=="Cancelled")} onBooking={onBooking} onSlot={onSlot}/>)}</div>{!filtered.length&&<Empty title="No vehicles match these filters"/>}</div></section>;
}

function ResourceRow({vehicle,days,cols,bookings,onBooking,onSlot}:{vehicle:Vehicle;days:Date[];cols:string;bookings:Booking[];onBooking:(b:Booking)=>void;onSlot:(v:string,p:string,r:string)=>void}){
 const rangeStart=days[0],rangeEnd=new Date(days[days.length-1].getTime()+86400000);const blocks=bookings.filter(b=>overlaps(localIso(rangeStart),localIso(rangeEnd),b.pickup,b.returnAt));
 return <div className="resourceRow" style={{gridTemplateColumns:cols}}><div className="resourceVehicle"><span>▰</span><p><b>{vehicle.name}</b><small>{vehicle.reg} · {vehicle.seats} seats</small></p></div>{days.map((d,i)=>{const end=new Date(d.getTime()+86400000);const occupied=blocks.some(b=>overlaps(localIso(d),localIso(end),b.pickup,b.returnAt))||!!(vehicle.maintenance&&overlaps(localIso(d),localIso(end),vehicle.maintenance.from,vehicle.maintenance.to));return <button aria-label={`Create booking for ${vehicle.name} on ${d.toDateString()}`} disabled={occupied} onClick={()=>onSlot(vehicle.id,`${localIso(d).slice(0,10)}T08:00`,`${localIso(end).slice(0,10)}T20:00`)} className={`${i===0?"today":""} ${d.getDay()===0||d.getDay()===6?"weekend":""} slot`} style={{gridColumn:i+2,gridRow:1}} key={i}>{!occupied&&<span>+</span>}</button>})}{blocks.map(b=>{const start=Math.max(0,Math.floor((new Date(b.pickup).setHours(0,0,0,0)-rangeStart.getTime())/86400000));const end=Math.min(days.length,Math.ceil((new Date(b.returnAt).getTime()-rangeStart.getTime())/86400000));const span=Math.max(1,end-start);return <button title={`${b.id}\n${b.customerName}\n${b.from} → ${b.to}\n${formatDateTime(b.pickup)} – ${formatDateTime(b.returnAt)}`} onClick={()=>onBooking(b)} key={b.id} className={`bookingBlock ${statusColor[b.status]}`} style={{gridColumn:`${start+2} / span ${span}`,gridRow:1}}><b>{b.customerName}</b><span>{b.from.replace(", Indore","")} → {b.to}</span><em>{b.status}</em></button>})}{vehicle.maintenance&&overlaps(localIso(rangeStart),localIso(rangeEnd),vehicle.maintenance.from,vehicle.maintenance.to)&&<button title={`${vehicle.maintenance.reason}\n${formatDateTime(vehicle.maintenance.from)} – ${formatDateTime(vehicle.maintenance.to)}`} className="bookingBlock red" style={{gridColumn:`${Math.max(0,Math.floor((new Date(vehicle.maintenance.from).setHours(0,0,0,0)-rangeStart.getTime())/86400000))+2} / span 2`,gridRow:1}}><b>Maintenance</b><span>{vehicle.maintenance.reason}</span><em>Unavailable</em></button>}</div>;
}

function AvailabilityChecker({bookings,onSelect}:{bookings:Booking[];onSelect:(v:Vehicle,p:string,r:string)=>void}){
 const [pickup,setPickup]=useState("2026-08-22T08:00"),[returnAt,setReturnAt]=useState("2026-08-24T20:00"),[category,setCategory]=useState("Innova Crysta"),[searched,setSearched]=useState(true),[loading,setLoading]=useState(false),[error,setError]=useState("");
 const relevant=vehicles.filter(v=>category==="All"||v.category===category);const booked=relevant.filter(v=>bookings.some(b=>b.status!=="Cancelled"&&(b.vehicleId===v.id||b.driverId===v.driverId)&&overlaps(pickup,returnAt,b.pickup,b.returnAt)));const maintenance=relevant.filter(v=>v.maintenance&&overlaps(pickup,returnAt,v.maintenance.from,v.maintenance.to));const available=relevant.filter(v=>!booked.includes(v)&&!maintenance.includes(v));
 function search(){if(new Date(returnAt)<=new Date(pickup)){setError("Expected return must be later than pickup time.");setSearched(false);return}setError("");setLoading(true);setTimeout(()=>{setLoading(false);setSearched(true)},450)}
 return <section className="checkerPage"><div className="searchCard card"><div className="searchSteps"><span className="done">1</span><i/><span className="done">2</span><i/><span className="done">3</span><i/><span className={searched?"done":""}>4</span></div><div className="checkerForm"><label>Pickup date & time<input type="datetime-local" value={pickup} onChange={e=>setPickup(e.target.value)}/></label><span>→</span><label>Expected return date & time<input type="datetime-local" value={returnAt} min={pickup} onChange={e=>setReturnAt(e.target.value)}/></label><label>Vehicle category<select value={category} onChange={e=>setCategory(e.target.value)}><option>All</option>{Array.from(new Set(vehicles.map(v=>v.category))).map(c=><option key={c}>{c}</option>)}</select></label><button className="btn" onClick={search}>⌕ Find available vehicles</button></div>{error&&<div className="inlineError">! {error}</div>}</div>
 {loading&&<div className="loading card"><i/><b>Checking vehicle and driver schedules…</b></div>}{searched&&!loading&&<><div className="resultSummary"><div><span>✓</span><p><b>{available.length} vehicles available</b><small>{formatDateTime(pickup)} → {formatDateTime(returnAt)}</small></p></div><p><b>{relevant.length}</b> matching vehicles checked　 <b>{booked.length}</b> already booked</p></div><VehicleGroup title="Available Vehicles" count={available.length} tone="green" vehicles={available} bookings={bookings} onSelect={v=>onSelect(v,pickup,returnAt)}/><VehicleGroup title="Already Booked" count={booked.length} tone="blue" vehicles={booked} bookings={bookings}/>{maintenance.length>0&&<VehicleGroup title="In Maintenance" count={maintenance.length} tone="red" vehicles={maintenance} bookings={bookings}/>}</>}</section>;
}

function VehicleGroup({title,count,tone,vehicles:items,bookings,onSelect}:{title:string;count:number;tone:string;vehicles:Vehicle[];bookings:Booking[];onSelect?:(v:Vehicle)=>void}){const [open,setOpen]=useState(true);return <section className="vehicleGroup card"><button className="groupHead" onClick={()=>setOpen(!open)}><span className={tone}>{count}</span><div><h3>{title}</h3><p>{title==="Available Vehicles"?"Vehicle and assigned driver are free for the full period.":"Unavailable during part or all of the requested period."}</p></div><i>{open?"⌃":"⌄"}</i></button>{open&&<div className="vehicleCards">{items.map(v=>{const driver=drivers.find(d=>d.id===v.driverId);const next=bookings.filter(b=>b.vehicleId===v.id&&new Date(b.pickup)>fixedNow).sort((a,b)=>+new Date(a.pickup)-+new Date(b.pickup))[0];return <article key={v.id}><div className="vehicleCardTop"><span className="vehicleGlyph">▰</span><div><h4>{v.name}</h4><p>{v.reg}</p></div><em className={`pill ${tone}`}>{title==="Available Vehicles"?"Available":title==="In Maintenance"?"Maintenance":"Booked"}</em></div><dl><div><dt>SEATING</dt><dd>{v.seats} passengers</dd></div><div><dt>DEFAULT DRIVER</dt><dd>{driver?.name}</dd></div><div><dt>CURRENT LOCATION</dt><dd>{v.location}</dd></div><div><dt>NEXT BOOKING</dt><dd>{next?formatDateTime(next.pickup):"No upcoming trip"}</dd></div></dl><div className="vehiclePrice"><span>Estimated rate <b>{money(v.rate)}/km</b></span>{onSelect?<button className="btn" onClick={()=>onSelect(v)}>Select vehicle →</button>:<button disabled>Unavailable</button>}</div></article>})}{!items.length&&<Empty title={`No ${title.toLowerCase()}`}/>}</div>}</section>}

function BookingWizard({draft,setDraft,step,setStep,amount,balance,onClose,onConfirm,success}:{draft:BookingDraft;setDraft:(v:BookingDraft|((p:BookingDraft)=>BookingDraft))=>void;step:number;setStep:(n:number)=>void;amount:number;balance:number;onClose:()=>void;onConfirm:()=>void;success:Booking|null}){
 const labels=["Customer Details","Trip Details","Vehicle & Driver","Pricing & Payment","Review & Confirm"];const validStep=()=>{if(step===1)return draft.customerName.trim()&&/^\d{10}$/.test(draft.phone.replace(/\s/g,""));if(step===2)return draft.from&&draft.to&&new Date(draft.returnAt)>new Date(draft.pickup);return true};
 const vehicle=vehicles.find(v=>v.id===draft.vehicleId),driver=drivers.find(d=>d.id===draft.driverId);
 return <div className="overlay"><section className="wizard"><header><div><span className="overline">CREATE BOOKING</span><h2>{success?"Booking confirmed":labels[step-1]}</h2><p>{success?success.id:`Step ${step} of 5 · Complete the details below`}</p></div><button onClick={onClose}>×</button></header><div className="wizardSteps">{labels.map((l,i)=><button key={l} className={step===i+1?"active":step>i+1?"done":""} onClick={()=>i+1<step&&setStep(i+1)}><span>{step>i+1?"✓":i+1}</span><b>{l}</b></button>)}</div><div className="wizardBody">
 {success?<Confirmation booking={success}/>:<>{step===1&&<div className="stepGrid"><Field label="Customer name"><input value={draft.customerName} onChange={e=>setDraft({...draft,customerName:e.target.value})}/></Field><Field label="Mobile number"><input inputMode="tel" value={draft.phone} onChange={e=>setDraft({...draft,phone:e.target.value})}/></Field><Field label="WhatsApp number"><input inputMode="tel" value={draft.whatsapp} onChange={e=>setDraft({...draft,whatsapp:e.target.value})}/></Field><Field label="Email address"><input type="email" value={draft.email} onChange={e=>setDraft({...draft,email:e.target.value})}/></Field></div>}
 {step===2&&<div className="stepGrid"><Field label="Pickup location"><input value={draft.from} onChange={e=>setDraft({...draft,from:e.target.value})}/></Field><Field label="Destination"><input value={draft.to} onChange={e=>setDraft({...draft,to:e.target.value})}/></Field><Field label="Pickup date & time"><input type="datetime-local" value={draft.pickup} onChange={e=>setDraft({...draft,pickup:e.target.value})}/></Field><Field label="Expected return"><input type="datetime-local" min={draft.pickup} value={draft.returnAt} onChange={e=>setDraft({...draft,returnAt:e.target.value})}/></Field>{new Date(draft.returnAt)<=new Date(draft.pickup)&&<div className="inlineError span2">! Return must be later than pickup.</div>}<Field label="Trip notes" wide><textarea value={draft.notes} onChange={e=>setDraft({...draft,notes:e.target.value})}/></Field></div>}
 {step===3&&<div className="stepGrid"><Field label="Vehicle"><select value={draft.vehicleId} onChange={e=>{const v=vehicles.find(x=>x.id===e.target.value)!;setDraft({...draft,vehicleId:v.id,driverId:v.driverId,rate:v.rate})}}>{vehicles.map(v=><option value={v.id} key={v.id}>{v.name} · {v.reg}</option>)}</select></Field><Field label="Driver"><select value={draft.driverId} onChange={e=>setDraft({...draft,driverId:e.target.value})}>{drivers.map(d=><option value={d.id} key={d.id}>{d.name} · {d.status}</option>)}</select></Field><div className="selectionSummary span2"><span className="vehicleGlyph">▰</span><p><b>{vehicle?.name}</b><small>{vehicle?.reg} · {vehicle?.seats} seats · {money(vehicle?.rate||0)}/km</small></p><i>+</i><span className="avatar">{driver?.name.split(" ").map(x=>x[0]).join("")}</span><p><b>{driver?.name}</b><small>{driver?.phone} · {driver?.status}</small></p></div><div className="safe span2">✓ Vehicle and driver conflict check will run before confirmation. 90-minute turnaround buffer enabled.</div></div>}
 {step===4&&<div className="stepGrid"><Field label="Rate per kilometre"><input type="number" value={draft.rate} onChange={e=>setDraft({...draft,rate:+e.target.value})}/></Field><Field label="Estimated kilometres"><input type="number" value={draft.estimatedKm} onChange={e=>setDraft({...draft,estimatedKm:+e.target.value})}/></Field><Field label="Estimated amount"><input readOnly value={money(amount)}/></Field><Field label="Advance received"><input type="number" value={draft.advance} onChange={e=>setDraft({...draft,advance:+e.target.value})}/></Field><div className="priceSummary span2"><span>Total estimate <b>{money(amount)}</b></span><span>Advance <b>{money(draft.advance)}</b></span><span>Pending balance <b>{money(balance)}</b></span></div></div>}
 {step===5&&<Review draft={draft} amount={amount} balance={balance}/>}</>}
 </div>{!success&&<footer><button className="secondaryBtn" onClick={step===1?onClose:()=>setStep(step-1)}>{step===1?"Cancel":"← Back"}</button>{step<5?<button className="btn" disabled={!validStep()} onClick={()=>setStep(step+1)}>Continue →</button>:<button className="btn" onClick={onConfirm}>Run conflict check & confirm</button>}</footer>}</section></div>;
}

function Field({label,children,wide}:{label:string;children:React.ReactNode;wide?:boolean}){return <label className={wide?"span2":""}><span>{label}</span>{children}</label>}
function Review({draft,amount,balance}:{draft:BookingDraft;amount:number;balance:number}){const v=vehicles.find(v=>v.id===draft.vehicleId),d=drivers.find(x=>x.id===draft.driverId);return <div className="review"><div><span className="overline">CUSTOMER</span><b>{draft.customerName}</b><p>{draft.phone} · {draft.email}</p></div><div><span className="overline">TRIP</span><b>{draft.from} → {draft.to}</b><p>{formatDateTime(draft.pickup)} to {formatDateTime(draft.returnAt)}</p></div><div><span className="overline">ASSIGNMENT</span><b>{v?.name} · {v?.reg}</b><p>{d?.name} · {d?.phone}</p></div><div className="reviewPrice"><span>Estimated total <b>{money(amount)}</b></span><span>Advance received <b>{money(draft.advance)}</b></span><span>Pending balance <b>{money(balance)}</b></span></div><div className="safe">✓ No changes will be saved until vehicle and driver schedules pass the final conflict check.</div></div>}
function Confirmation({booking}:{booking:Booking}){const v=vehicles.find(v=>v.id===booking.vehicleId),d=drivers.find(x=>x.id===booking.driverId);return <div className="confirmation"><div className="successIcon">✓</div><h3>Booking confirmed successfully</h3><p>The fleet calendar, dashboard KPIs and upcoming trips have been updated.</p><div className="confirmationCard"><header><Brand/><span className="pill green">CONFIRMED</span></header><h4>{booking.id}</h4><div><span>Customer<b>{booking.customerName}</b></span><span>Route<b>{booking.from} → {booking.to}</b></span><span>Vehicle<b>{v?.name} · {v?.reg}</b></span><span>Driver<b>{d?.name}</b></span><span>Pickup<b>{formatDateTime(booking.pickup)}</b></span><span>Pending<b>{money(booking.total-booking.advance)}</b></span></div></div><div className="confirmationActions"><a className="btn whatsapp" target="_blank" href={`https://wa.me/91${booking.phone.replace(/\D/g,"")}?text=${encodeURIComponent(`Dear ${booking.customerName}, your Shreenath Tours & Travels booking ${booking.id} is confirmed. Vehicle: ${v?.name}. Pickup: ${formatDateTime(booking.pickup)}. Route: ${booking.from} to ${booking.to}.`)}`}>WhatsApp confirmation</a><button className="secondaryBtn" onClick={()=>window.print()}>Print booking</button></div></div>}

function ConflictModal({conflict,draft,alternatives,onClose,onAlternative}:{conflict:Booking;draft:BookingDraft;alternatives:Vehicle[];onClose:()=>void;onAlternative:(v:Vehicle)=>void}){const vehicle=vehicles.find(v=>v.id===conflict.vehicleId);const sameDriver=conflict.driverId===draft.driverId;return <div className="overlay modalLayer"><section className="conflictModal"><button className="modalClose" onClick={onClose}>×</button><div className="conflictIcon">!</div><span className="overline errorText">BOOKING BLOCKED</span><h2>Booking Conflict Detected</h2><p>The selected {sameDriver?"vehicle or driver is":"vehicle is"} already assigned during the requested period. Your entered details are preserved.</p><div className="conflictDetails"><div><span>CONFLICTING BOOKING</span><b>{conflict.id}</b></div><div><span>CUSTOMER</span><b>{conflict.customerName}</b></div><div><span>VEHICLE</span><b>{vehicle?.name} · {vehicle?.reg}</b></div><div><span>ROUTE</span><b>{conflict.from} → {conflict.to}</b></div><div><span>EXISTING SCHEDULE</span><b>{formatDateTime(conflict.pickup)} → {formatDateTime(conflict.returnAt)}</b></div><div><span>REQUESTED SCHEDULE</span><b>{formatDateTime(draft.pickup)} → {formatDateTime(draft.returnAt)}</b></div></div><div className="blockReason"><b>Reason for blocking</b><p>Requested pickup begins before the existing trip returns, and requested return occurs after the existing trip starts. Saving would create an overlapping assignment.</p></div><h3>Available alternatives</h3><p className="subcopy">Same or similar category, genuinely free for the complete period.</p>{alternatives.map(v=><button className="alternativeRow" key={v.id} onClick={()=>onAlternative(v)}><span className="vehicleGlyph">▰</span><p><b>{v.name}</b><small>{v.reg} · {v.seats} seats · {drivers.find(d=>d.id===v.driverId)?.name}</small></p><em>Use this vehicle →</em></button>)}<button className="secondaryBtn full" onClick={onClose}>Review booking details</button></section></div>}

function BookingDrawer({booking,onClose,onDuplicate}:{booking:Booking;onClose:()=>void;onDuplicate:()=>void}){const v=vehicles.find(x=>x.id===booking.vehicleId),d=drivers.find(x=>x.id===booking.driverId);return <div className="drawerLayer" onClick={onClose}><aside className="drawer" onClick={e=>e.stopPropagation()}><header><div><span className="overline">BOOKING DETAILS</span><h2>{booking.id}</h2></div><button onClick={onClose}>×</button></header><span className={`pill ${statusColor[booking.status]}`}>{booking.status}</span><div className="drawerRoute"><span>{booking.from}</span><i>→</i><span>{booking.to}</span></div><dl><div><dt>Customer</dt><dd>{booking.customerName}<small>{booking.phone}</small></dd></div><div><dt>Vehicle</dt><dd>{v?.name}<small>{v?.reg}</small></dd></div><div><dt>Driver</dt><dd>{d?.name}<small>{d?.phone}</small></dd></div><div><dt>Pickup</dt><dd>{formatDateTime(booking.pickup)}</dd></div><div><dt>Expected return</dt><dd>{formatDateTime(booking.returnAt)}</dd></div><div><dt>Source</dt><dd>{booking.source}</dd></div></dl><div className="drawerMoney"><span>Total<b>{money(booking.total)}</b></span><span>Advance<b>{money(booking.advance)}</b></span><span>Pending<b>{money(booking.total-booking.advance)}</b></span></div><a className="btn whatsapp full" href={`https://wa.me/91${booking.phone}`} target="_blank">WhatsApp customer</a><button className="secondaryBtn full" onClick={onDuplicate}>Create overlapping booking test</button></aside></div>}

function BookingsPage({bookings,onOpen,onNew}:{bookings:Booking[];onOpen:(b:Booking)=>void;onNew:()=>void}){const [q,setQ]=useState(""),[filter,setFilter]=useState("All");const rows=bookings.filter(b=>(filter==="All"||b.status===filter)&&(b.id+b.customerName+b.phone+b.to).toLowerCase().includes(q.toLowerCase()));return <section className="dataPage card"><div className="dataToolbar"><div className="tableSearch">⌕<input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search booking, customer, phone or route"/></div><select value={filter} onChange={e=>setFilter(e.target.value)}><option>All</option>{Array.from(new Set(bookings.map(b=>b.status))).map(s=><option key={s}>{s}</option>)}</select><button className="btn" onClick={onNew}>+ Create booking</button></div><div className="dataTable bookingTable"><div className="dataHead"><b>BOOKING</b><b>CUSTOMER</b><b>TRIP & SCHEDULE</b><b>VEHICLE / DRIVER</b><b>PAYMENT</b><b>STATUS</b><b/></div>{rows.slice(0,30).map(b=><button className="dataRow" key={b.id} onClick={()=>onOpen(b)}><span><b>{b.id}</b><small>{b.source}</small></span><span><b>{b.customerName}</b><small>{b.phone}</small></span><span><b>{b.from} → {b.to}</b><small>{formatDateTime(b.pickup)}</small></span><span><b>{vehicles.find(v=>v.id===b.vehicleId)?.name}</b><small>{drivers.find(d=>d.id===b.driverId)?.name}</small></span><span><b>{money(b.total)}</b><small>{money(b.total-b.advance)} pending</small></span><span><em className={`pill ${statusColor[b.status]}`}>{b.status}</em></span><i>›</i></button>)}{!rows.length&&<Empty title="No bookings found"/>}</div></section>}

function VehiclesPage({bookings}:{bookings:Booking[]}){const [q,setQ]=useState(""),[cat,setCat]=useState("All");const list=vehicles.filter(v=>(cat==="All"||v.category===cat)&&(v.name+v.reg).toLowerCase().includes(q.toLowerCase()));return <section><div className="dataToolbar card"><div className="tableSearch">⌕<input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search vehicle or registration"/></div><select value={cat} onChange={e=>setCat(e.target.value)}><option>All</option>{Array.from(new Set(vehicles.map(v=>v.category))).map(c=><option key={c}>{c}</option>)}</select><span className="recordCount">{list.length} vehicles</span></div><div className="fleetManage">{list.map(v=>{const active=bookings.find(b=>b.vehicleId===v.id&&new Date(b.pickup)<=fixedNow&&new Date(b.returnAt)>=fixedNow);const status=v.maintenance?"Maintenance":active?"On Trip":"Available";return <article className="card" key={v.id}><div><span className="vehicleGlyph">▰</span><em className={`pill ${status==="Available"?"green":status==="On Trip"?"navy":"red"}`}>{status}</em></div><h3>{v.name}</h3><p>{v.reg} · {v.category}</p><dl><span>Seats<b>{v.seats}</b></span><span>Driver<b>{drivers.find(d=>d.id===v.driverId)?.name.split(" ")[0]}</b></span><span>Rate<b>{money(v.rate)}/km</b></span></dl>{v.maintenance?<div className="vehicleAlert">! {v.maintenance.reason}</div>:<button onClick={()=>alert(`${v.name}\n${v.reg}\nNext booking: ${bookings.find(b=>b.vehicleId===v.id&&new Date(b.pickup)>fixedNow)?.pickup||"None"}`)}>View vehicle profile →</button>}</article>})}</div></section>}

function DriversPage({bookings}:{bookings:Booking[]}){const [filter,setFilter]=useState("All");const list=drivers.filter(d=>filter==="All"||d.status===filter);return <section className="dataPage card"><div className="dataToolbar"><div className="segmented">{["All","Available","On Trip","Leave"].map(s=><button className={filter===s?"active":""} key={s} onClick={()=>setFilter(s)}>{s}</button>)}</div><span className="recordCount">{list.length} drivers</span></div><div className="driverGrid">{list.map(d=>{const trip=bookings.find(b=>b.driverId===d.id&&new Date(b.pickup)<=fixedNow&&new Date(b.returnAt)>=fixedNow);return <article key={d.id}><span className="driverAvatar">{d.name.split(" ").map(x=>x[0]).join("")}</span><div><h3>{d.name}</h3><p>{d.phone} · {d.license}</p></div><em className={`pill ${d.status==="Available"?"green":d.status==="On Trip"?"navy":"grey"}`}>{d.status}</em><dl><span>Assigned vehicle<b>{vehicles.find(v=>v.id===d.vehicleId)?.name||"Pool driver"}</b></span><span>Current trip<b>{trip?trip.to:"No active trip"}</b></span><span>Total trips<b>{d.trips}</b></span><span>Licence expiry<b>{new Date(d.licenseExpiry).toLocaleDateString("en-IN",{day:"numeric",month:"short",year:"numeric"})}</b></span></dl><a href={`tel:${d.phone}`}>Call driver</a></article>})}</div></section>}

function CustomersPage({bookings,onNew}:{bookings:Booking[];onNew:(c:Customer)=>void}){const [q,setQ]=useState("");const list=customers.filter(c=>(c.name+c.phone).toLowerCase().includes(q.toLowerCase()));return <section className="dataPage card"><div className="dataToolbar"><div className="tableSearch">⌕<input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search customer or mobile"/></div><span className="recordCount">80 customers</span></div><div className="customerGrid">{list.slice(0,40).map(c=><article key={c.id}><header><span>{c.name.split(" ").map(x=>x[0]).join("")}</span><div><h3>{c.name}</h3><p>{c.phone}</p></div></header><dl><span>Total trips<b>{bookings.filter(b=>b.customerId===c.id).length||c.trips}</b></span><span>Lifetime value<b>{money(c.spending)}</b></span><span>Outstanding<b className={c.outstanding?"due":""}>{money(c.outstanding)}</b></span></dl><div><a href={`https://wa.me/91${c.phone}`} target="_blank">WhatsApp</a><button onClick={()=>onNew(c)}>Create booking</button></div></article>)}</div></section>}

function PaymentsPage({bookings,onOpen,onToast}:{bookings:Booking[];onOpen:(b:Booking)=>void;onToast:(s:string)=>void}){const pending=bookings.filter(b=>b.status!=="Cancelled"&&b.total>b.advance);const total=bookings.reduce((s,b)=>s+b.total,0),advance=bookings.reduce((s,b)=>s+b.advance,0);return <section><div className="paymentKpis">{[["Total booking value",money(total)],["Advance received",money(advance)],["Collected",money(total-pending.reduce((s,b)=>s+(b.total-b.advance),0))],["Pending payments",money(pending.reduce((s,b)=>s+(b.total-b.advance),0))]].map(x=><div className="card" key={x[0]}><small>{x[0]}</small><b>{x[1]}</b></div>)}</div><div className="dataPage card"><CardHead title="Pending Collections" sub={`${pending.length} bookings require payment follow-up`} action="Export" onAction={()=>onToast("Payment report exported successfully.")}/><div className="paymentList">{pending.slice(0,25).map(b=><article key={b.id}><span className="dueIcon">₹</span><p><b>{b.customerName}</b><small>{b.id} · {b.to} · {formatDateTime(b.returnAt)}</small></p><strong>{money(b.total-b.advance)}</strong><a target="_blank" href={`https://wa.me/91${b.phone}?text=${encodeURIComponent(`Dear ${b.customerName}, a payment of ${money(b.total-b.advance)} is pending for booking ${b.id}. Thank you, Shreenath Tours & Travels.`)}`}>Send reminder</a><button onClick={()=>onOpen(b)}>View</button></article>)}</div></div></section>}

function EnquiriesPage({enquiries,setEnquiries,onBooking}:{enquiries:Enquiry[];setEnquiries:(f:(p:Enquiry[])=>Enquiry[])=>void;onBooking:(e:Enquiry)=>void}){return <section className="dataPage card"><div className="dataToolbar"><h3>Website booking enquiries</h3><span className="recordCount">{enquiries.filter(e=>e.status==="New").length} new</span></div><div className="enquiryList">{enquiries.map(e=><article key={e.id}><span className={e.status==="New"?"newDot":""}/><p><b>{e.name}</b><small>{e.phone} · {e.route} · {e.tripType}</small></p><time>{e.date}</time><em className={`pill ${e.status==="New"?"blue":"green"}`}>{e.status}</em><a href={`tel:${e.phone}`}>Call</a><button onClick={()=>setEnquiries(p=>p.map(x=>x.id===e.id?{...x,status:"Contacted"}:x))}>Mark contacted</button><button className="btn" onClick={()=>onBooking(e)}>Create booking</button></article>)}{!enquiries.length&&<Empty title="No website enquiries yet"/>}</div></section>}

function ReportsPage({bookings,onToast}:{bookings:Booking[];onToast:(s:string)=>void}){const monthly=[5.2,6.1,5.8,7.3,7.9,8.4];const top=vehicles.slice(0,5).map((v,i)=>({name:v.name,value:91000-i*8500}));return <section><div className="reportTop"><div className="card"><small>Monthly Revenue</small><b>₹8.4L</b><em>↑ 12.4% from July</em></div><div className="card"><small>Trips This Month</small><b>{bookings.filter(b=>b.pickup.startsWith("2026-08")).length}</b><em>Across 40 vehicles</em></div><div className="card"><small>Fleet Utilisation</small><b>74%</b><em>Target 78%</em></div><div className="card"><small>Average Booking Value</small><b>{money(Math.round(bookings.reduce((s,b)=>s+b.total,0)/bookings.length))}</b><em>All booking sources</em></div></div><div className="reportGrid"><section className="card revenueChart"><CardHead title="Monthly Revenue" sub="March – August 2026" action="Export PDF" onAction={()=>onToast("Revenue report exported as PDF.")}/><div>{monthly.map((n,i)=><span key={i}><b style={{height:`${n/8.4*100}%`}} title={`₹${n} lakh`}/><small>{["Mar","Apr","May","Jun","Jul","Aug"][i]}</small><em>₹{n}L</em></span>)}</div></section><section className="card topVehicles"><CardHead title="Top Performing Vehicles" sub="Revenue this month" action="Excel" onAction={()=>onToast("Vehicle revenue exported to Excel.")}/>{top.map((v,i)=><div key={v.name}><span>{i+1}</span><p><b>{v.name}</b><small>{12-i} trips</small></p><strong>{money(v.value)}</strong></div>)}</section></div></section>}

function NotificationsPage({onNavigate}:{onNavigate:(t:Tab)=>void}){const items=[["Vehicle booking conflict blocked","Crysta 04 · overlapping request prevented","2 min ago","Bookings"],["New website enquiry","Kunal Mehta · Indore to Mumbai","48 min ago","Website Enquiries"],["Insurance expires soon","Innova Crysta 07 · 8 days remaining","Today","Vehicles"],["Payment follow-up due","Amit Jain · ₹15,000 pending","Today","Payments"],["Driver licence expiry","Pradeep Tomar · 14 days remaining","Yesterday","Drivers"]] as [string,string,string,Tab][];return <section className="notificationPage card">{items.map((x,i)=><button key={x[0]} onClick={()=>onNavigate(x[3])}><i className={i===0||i>1?"alertIcon":"infoIcon"}>{i===1?"✉":"!"}</i><p><b>{x[0]}</b><small>{x[1]}</small></p><time>{x[2]}</time><span>View →</span></button>)}</section>}
function SettingsPage({onToast}:{onToast:(s:string)=>void}){const [buffer,setBuffer]=useState(90),[alerts,setAlerts]=useState(true);return <section className="settings card"><h3>Booking rules</h3><p>Rules apply to availability, vehicle assignment and conflict checks.</p><label><span>Turnaround buffer<small>Minimum time required between two vehicle trips.</small></span><select value={buffer} onChange={e=>setBuffer(+e.target.value)}><option value={60}>60 minutes</option><option value={90}>90 minutes</option><option value={120}>120 minutes</option></select></label><label><span>Peak-season alerts<small>Warn booking staff on dates above 90% utilisation.</small></span><input type="checkbox" checked={alerts} onChange={e=>setAlerts(e.target.checked)}/></label><button className="btn" onClick={()=>onToast("Settings saved successfully.")}>Save settings</button></section>}
function Empty({title}:{title:string}){return <div className="empty"><span>◇</span><b>{title}</b><p>Try changing the current filters or date range.</p></div>}
