"use client";
import { useMemo, useState } from "react";

type Status = "AVAILABLE"|"ON TRIP"|"BOOKED"|"RETURNING"|"MAINTENANCE";
const fleet:{name:string;reg:string;status:Status;detail:string}[]=[
 {name:"Innova Crysta 04",reg:"MP09 XX 4554",status:"AVAILABLE",detail:"Ready for immediate booking"},
 {name:"Innova Crysta 02",reg:"MP09 XX 2394",status:"AVAILABLE",detail:"Next booking 25 Aug"},
 {name:"Innova Crysta 06",reg:"MP09 XX 7812",status:"AVAILABLE",detail:"Ready for immediate booking"},
 {name:"Toyota Innova 01",reg:"MP09 XX 1234",status:"ON TRIP",detail:"Amit Jain · Ujjain · returns 8:30 PM"},
 {name:"Swift Dzire 07",reg:"MP09 XX 9021",status:"RETURNING",detail:"Airport drop · returns 5:00 PM"},
 {name:"Maruti Ertiga 03",reg:"MP09 XX 6754",status:"MAINTENANCE",detail:"Service due · available 23 Aug"},
];
const services=["Local Taxi","Outstation Trips","Airport Pickup & Drop","Corporate Travel","Wedding Car Rental","Family Tours","One Way Taxi","Multi-Day Trips"];

export default function Home(){const [screen,setScreen]=useState<"site"|"dashboard">("site");return screen==="site"?<Website open={()=>setScreen("dashboard")}/>:<Dashboard close={()=>setScreen("site")}/>}

function Website({open}:{open:()=>void}){return <main className="site">
 <nav className="nav wrap"><Brand/><div className="links"><a href="#services">Services</a><a href="#fleet">Our Fleet</a><a href="#about">About</a><a href="#contact">Contact</a></div><div className="navend"><button className="quiet" onClick={open}>Staff dashboard</button><a className="btn" href="#book">Book a trip</a></div></nav>
 <section className="hero"><div className="wrap heroGrid"><div className="heroCopy"><span className="eyebrow">● TRUSTED TRAVEL PARTNER SINCE 2012</span><h1>Your Journey.<br/><em>Our Responsibility.</em></h1><p>Reliable cars, professional drivers and comfortable travel for local, airport and outstation trips.</p><div className="actions"><a className="btn large" href="#book">Book your trip <b>→</b></a><button className="outline" onClick={open}>Check available cars</button></div><div className="trust">✓ Verified drivers　 ✓ Transparent pricing　 ✓ Sanitised cars</div></div><div className="heroArt"><div className="photo"><div className="route"><b>INDORE</b><span>→</span><b>ANYWHERE</b></div></div><div className="float rating"><span>★★★★★</span><b>4.9/5 traveller rating</b></div><div className="float phone"><span>☎</span><div><small>24×7 Booking desk</small><b>+91 98260 12345</b></div></div></div></div><div className="wrap stats">{[["40+","Vehicles"],["5,000+","Trips completed"],["2,500+","Happy travellers"],["24×7","Booking support"]].map(x=><div key={x[1]}><b>{x[0]}</b><span>{x[1]}</span></div>)}</div></section>
 <section className="intro wrap" id="services"><div><span className="eyebrow">TRAVEL, DONE RIGHT</span><h2>Every trip deserves<br/>a better experience.</h2></div><p>From the first call to the final drop, our team handles every detail so you can simply enjoy the journey.</p></section>
 <section className="services wrap">{services.map((s,i)=><article key={s}><span>0{i+1}</span><h3>{s}</h3><p>{i%2?"Comfortable travel with experienced drivers and transparent fares.":"Reliable, on-time service planned around your schedule."}</p><div><b>From ₹{i%3===0?"1,499":"12/km"}</b><button>Book now →</button></div></article>)}</section>
 <section className="cta" id="book"><div className="wrap"><div><span className="eyebrow">COMPLETE BUSINESS MANAGEMENT</span><h2>Know your entire travel<br/>business from one dashboard.</h2><p>No double bookings. No vehicle confusion. No spreadsheet headaches.</p></div><button className="gold" onClick={open}>Explore live dashboard →</button></div></section>
 </main>}

function Brand(){return <div className="brand"><span>S</span><div><b>Shreenath</b><small>Tours & Travels</small></div></div>}

function Dashboard({close}:{close:()=>void}){const [tab,setTab]=useState("Dashboard");const [modal,setModal]=useState(false);const [result,setResult]=useState(false);const [booked,setBooked]=useState(false);const [conflict,setConflict]=useState(false);const available=useMemo(()=>fleet.filter(v=>v.status==="AVAILABLE"),[]);return <main className="shell">
 <aside><Brand/><nav>{["Dashboard","Bookings","Fleet Calendar","Availability Checker","Trips","Customers","Vehicles","Drivers","Payments","Reports","Notifications","Website Enquiries","Settings"].map((x,i)=><button onClick={()=>setTab(x)} className={tab===x?"active":""} key={x}><i>{["▦","▣","▤","⌕","↗","♙","▰","♟","₹","▥","♢","✉","⚙"][i]}</i>{x}</button>)}</nav><button className="back" onClick={close}>← Public website</button><div className="user"><span>AS</span><div><b>Ankit Sharma</b><small>Owner · Super Admin</small></div></div></aside>
 <section className="work"><header><div><span className="eyebrow">OPERATIONS OVERVIEW</span><h2>{tab}</h2><p>Friday, 21 August 2026 · Indore</p></div><div className="tools"><button>⌕ Search anything</button><button>♢ <sup>5</sup></button><button className="btn" onClick={()=>setModal(true)}>+ New booking</button></div></header>
 {tab!=="Dashboard"?<Module name={tab} onBack={()=>setTab("Dashboard")}/>:<>
 <div className="finder"><i/><div><b>Quick availability check</b><small>Find the right car in seconds</small></div><label><small>PICKUP</small><b>22 Aug · 08:00</b></label><span>→</span><label><small>RETURN</small><b>24 Aug · 20:00</b></label><label><small>CATEGORY</small><b>Innova Crysta⌄</b></label><button onClick={()=>setResult(true)}>Find available vehicles</button></div>
 {result&&<div className="results"><div><span>✓</span><p><b>3 Innova Crystas available</b><small>22 Aug, 8:00 AM → 24 Aug, 8:00 PM</small></p></div>{available.map(v=><button key={v.reg} onClick={()=>setModal(true)}><b>{v.name}</b><small>{v.reg}</small><span>Select →</span></button>)}</div>}
 <div className="kpis">{[["Total fleet","40","All vehicles"],["Available today","18","Ready to assign"],["On trip","14","Across 9 cities"],["Upcoming bookings","21","Next 7 days"],["Today revenue","₹48,500","↑ 12% vs yesterday"],["Outstanding","₹1,26,000","8 payments pending"]].map((x,i)=><article key={x[0]}><span className={`dot d${i}`}>◆</span><small>{x[0]}</small><b>{x[1]}</b><em>{x[2]}</em></article>)}</div>
 <div className="grid"><section className="panel fleet"><div className="panelHead"><div><h3>Live Fleet Status</h3><p>40 vehicles · Updated just now</p></div><div><button className="picked">All 40</button><button>Available 18</button><button>On trip 14</button></div></div><div className="vehicleRows">{fleet.slice(0,5).map(v=><article key={v.reg}><div className="car">▰</div><p><b>{v.name}</b><small>{v.reg}</small></p><span className={`badge ${v.status.replace(" ","").toLowerCase()}`}><i/>{booked&&v.reg==="MP09 XX 4554"?"BOOKED":v.status}</span><em>{booked&&v.reg==="MP09 XX 4554"?"Rahul Sharma · Jaipur · 22–24 Aug":v.detail}</em><button onClick={()=>{if(v.reg==="MP09 XX 4554"&&booked)setConflict(true)}}>•••</button></article>)}</div><button className="view">View all 40 vehicles →</button></section>
 <section className="panel departures"><div className="panelHead"><div><h3>Upcoming Departures</h3><p>Today · 21 August</p></div><button>View all</button></div>{[["06:00","Indore → Bhopal","Innova 04 · Rajesh"],["07:30","Airport → Vijay Nagar","Dzire 07 · Suresh"],["09:00","Indore → Ujjain","Ertiga 02 · Ramesh"],["11:15","Indore → Dewas","Crysta 06 · Manoj"]].map(x=><div className="trip" key={x[0]}><b>{x[0]}<small> AM</small></b><i/><p><strong>{x[1]}</strong><span>{x[2]}</span></p></div>)}</section></div>
 <div className="lower"><section className="panel calendar"><div className="panelHead"><div><h3>Fleet Availability</h3><p>21–25 August · Week view</p></div><button onClick={()=>setTab("Fleet Calendar")}>Open full calendar ↗</button></div><div className="matrix"><b>Vehicle</b>{[21,22,23,24,25].map(d=><b key={d}>{d} Aug</b>)}{["Innova 01","Crysta 04","Dzire 07","Ertiga 03"].map((v,r)=><div className="matrixrow" key={v}><strong>{v}</strong>{[0,1,2,3,4].map(c=><span className={(r+c)%4===0?"busy":(r===3&&c<2?"maint":"free")} key={c}>{(r+c)%4===0?"Booked":r===3&&c<2?"Service":"Free"}</span>)}</div>)}</div></section><section className="panel alert"><span>⚠</span><div><small>PEAK SEASON ALERT</small><h3>23 October is 95% booked</h3><p>38 of 40 cars assigned. Only 2 vehicles available.</p><button>Open Peak Season View →</button></div></section></div></>}
 </section>
 {modal&&<div className="overlay"><form className="modal" onSubmit={e=>{e.preventDefault();setModal(false);setBooked(true)}}><button type="button" className="x" onClick={()=>setModal(false)}>×</button><span className="eyebrow">NEW BOOKING</span><h2>Assign an available vehicle</h2><p>Availability verified for 22–24 August 2026</p><div className="formgrid"><label>Customer name<input required defaultValue="Rahul Sharma"/></label><label>Mobile number<input required defaultValue="98260 45678"/></label><label>Pickup location<input defaultValue="Indore"/></label><label>Destination<input defaultValue="Jaipur"/></label><label>Pickup date & time<input defaultValue="22 Aug 2026, 08:00"/></label><label>Return date & time<input defaultValue="24 Aug 2026, 20:00"/></label><label className="wide">Vehicle<select defaultValue="MP09 XX 4554"><option>Innova Crysta 04 · MP09 XX 4554</option><option>Innova Crysta 02 · MP09 XX 2394</option></select></label></div><div className="safe">✓ No scheduling conflicts found</div><button className="btn submit">Confirm booking · ₹18,500</button></form></div>}
 {conflict&&<div className="overlay"><div className="modal conflict"><button className="x" onClick={()=>setConflict(false)}>×</button><span className="warning">!</span><h2>Booking Conflict Detected</h2><p>This vehicle is already assigned to another trip during the selected dates.</p><div className="conflictbox"><b>Innova Crysta 04 · MP09 XX 4554</b><span>22 Aug 2026, 8:00 AM → 24 Aug 2026, 8:00 PM</span><small>Rahul Sharma · Indore → Jaipur</small></div><h4>Recommended available vehicles</h4>{available.slice(1).map(v=><button className="alternative" key={v.reg}><span>▰</span><p><b>{v.name}</b><small>{v.reg}</small></p><em>Available →</em></button>)}<button className="outline full" onClick={()=>setConflict(false)}>Cancel and review booking</button></div></div>}
 </main>}

function Module({name,onBack}:{name:string;onBack:()=>void}){return <section className="module panel"><button className="quiet" onClick={onBack}>← Back to overview</button><div className="moduleHero"><div><span className="eyebrow">SHREENATH OPERATIONS</span><h2>{name}</h2><p>This workspace is ready with search, filters, realistic demo records and quick actions.</p></div><button className="btn">+ Add new</button></div><div className="table"><div className="tableHead"><b>REFERENCE</b><b>DETAILS</b><b>STATUS</b><b>AMOUNT / DATE</b><b>ACTION</b></div>{[1,2,3,4,5,6].map(i=><div className="tableRow" key={i}><b>STT-2026-00{80+i}</b><span>{["Amit Jain","Rahul Sharma","Neha Agrawal","Vikram Singh","Pooja Mehta","Rohan Patel"][i-1]}<small>Indore → {i%2?"Udaipur":"Bhopal"}</small></span><em className="badge available">● CONFIRMED</em><span>₹{(8500+i*1200).toLocaleString("en-IN")}<small>{21+i} Aug 2026</small></span><button>View →</button></div>)}</div></section>}
